name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  testthat:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      CREA_DB_PRODUCTION: ${{ secrets.CREA_DB_PRODUCTION }}
      AGSI_API_KEY: ${{ secrets.AGSI_API_KEY }}
      API_KEY: ${{ secrets.API_KEY }}
      EMBER_KEY: ${{ secrets.EMBER_KEY }}
      EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::testthat
          needs: testthat
      - name: Run testthat
        run: Rscript -e 'testthat::test_local()'
